name: Deploy to EC2

on:
  push:
    branches:
      - "**" # This triggers the workflow on push to any branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2

      - name: Set up SSH key and whitelist EC2 IP address
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Create .env file dynamically
        env:
          ENV: ${{ secrets.ENV }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        run: |
          echo "ENV=${ENV}" >> .env
          echo "EC2_USERNAME=${EC2_USERNAME}" >> .env
          ls -la

      - name: Check .env contents
        run: |
          cat .env
          ls

      - name: Copy files to remote server
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        run: scp -r * $EC2_USERNAME@$EC2_HOST:/home/ubuntu/

      - name: Clean up SSH key
        if: always()
        run: rm -f ~/.ssh/id_rsa
